<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-KarraGameCorner-f9fbdfe7-616f-4c16-9c9d-21e43e936ce4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Pages\Store.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Pages\About.razor" />
    <_ContentIncludedByDefault Remove="Components\Pages\Store.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Pages\About.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KarraGameCorner.Shared\KarraGameCorner.Shared.csproj" />
  </ItemGroup>

</Project>
